/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decoder_bf.h)                                              */
/* BINDTOOL_HEADER_FILE_HASH(d3b8b964844cbb489942e7e9a79c688d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/op25/decoder_bf.h>
// pydoc.h is automatically generated in the build directory
#include <decoder_bf_pydoc.h>

void bind_decoder_bf(py::module& m)
{

    using decoder_bf    = ::gr::op25::decoder_bf;


    py::class_<decoder_bf, gr::block, gr::basic_block,
        std::shared_ptr<decoder_bf>>(m, "decoder_bf", D(decoder_bf))

        .def(py::init(&decoder_bf::make),
           D(decoder_bf,make)
        )
        




        
        .def("destination",&decoder_bf::destination,       
            D(decoder_bf,destination)
        )


        
        .def("get_msgq",&decoder_bf::get_msgq,       
            D(decoder_bf,get_msgq)
        )


        
        .def("set_msgq",&decoder_bf::set_msgq,       
            py::arg("msgq"),
            D(decoder_bf,set_msgq)
        )

        ;




}








