/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pcap_source_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f7beb8e8b79396426cc5de9ec3b61ae1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/op25/pcap_source_b.h>
// pydoc.h is automatically generated in the build directory
#include <pcap_source_b_pydoc.h>

void bind_pcap_source_b(py::module& m)
{

    using pcap_source_b    = ::gr::op25::pcap_source_b;


    py::class_<pcap_source_b, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pcap_source_b>>(m, "pcap_source_b", D(pcap_source_b))

        .def(py::init(&pcap_source_b::make),
           py::arg("path"),
           py::arg("delay"),
           D(pcap_source_b,make)
        )
        



        ;




}








