/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(frame_assembler.h) */
/* BINDTOOL_HEADER_FILE_HASH(6270eff3a7bd5d7eeee962e8b155596f) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/op25_repeater/frame_assembler.h>
// pydoc.h is automatically generated in the build directory
#include <frame_assembler_pydoc.h>

void bind_frame_assembler(py::module &m) {

  using frame_assembler = ::gr::op25_repeater::frame_assembler;
  using op25_decode_stats = ::gr::op25_repeater::op25_decode_stats;

  py::class_<op25_decode_stats>(m, "op25_decode_stats")
      .def_readonly("tsbk_attempted", &op25_decode_stats::tsbk_attempted)
      .def_readonly("tsbk_passed",    &op25_decode_stats::tsbk_passed)
      .def_readonly("pdu_attempted",  &op25_decode_stats::pdu_attempted)
      .def_readonly("pdu_passed",     &op25_decode_stats::pdu_passed)
      .def_readonly("timeout_count",  &op25_decode_stats::timeout_count)
      ;

  py::class_<frame_assembler, gr::block, gr::basic_block,
             std::shared_ptr<frame_assembler>>(m, "frame_assembler",
                                               D(frame_assembler))

      .def(py::init(&frame_assembler::make), py::arg("options"),
           py::arg("debug"), py::arg("msgq_id"), py::arg("queue"),
           D(frame_assembler, make))

      .def("set_debug", &frame_assembler::set_debug, py::arg("debug"),
           D(frame_assembler, set_debug))

      .def("control", &frame_assembler::control, py::arg("args"),
           D(frame_assembler, control))

      .def("get_decode_stats", &frame_assembler::get_decode_stats)

      ;
}
