/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ysf_tx_sb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3f99637b436cc582b9fa2b53f49be741)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/op25_repeater/ysf_tx_sb.h>
// pydoc.h is automatically generated in the build directory
#include <ysf_tx_sb_pydoc.h>

void bind_ysf_tx_sb(py::module& m)
{

    using ysf_tx_sb    = ::gr::op25_repeater::ysf_tx_sb;


    py::class_<ysf_tx_sb, gr::block, gr::basic_block,
        std::shared_ptr<ysf_tx_sb>>(m, "ysf_tx_sb", D(ysf_tx_sb))

        .def(py::init(&ysf_tx_sb::make),
           py::arg("versbose_flag"),
           py::arg("conf_file"),
           py::arg("fullrate_mode"),
           D(ysf_tx_sb,make)
        )
        




        
        .def("set_gain_adjust",&ysf_tx_sb::set_gain_adjust,       
            py::arg("gain_adjust"),
            D(ysf_tx_sb,set_gain_adjust)
        )

        ;




}








